### ISSUE TITLE
Pull request -> production

### ISSUE THREAD

**Issue by JLCochardSFA** [SwissFederalArchives/lindas-admin-ch#11]
@ludovicm67 : j'ai fait un pull request pour mettre la version test en production. Il y a quelques messages d'erreur mais je ne sais pas s'ils sont bloquants ou pas. Peux-tu regarder? 
Jean-Luc

**Comment by ludovicm67** [comment]
@JLCochardSFA Je m'en occupe en début de semaine prochaine, je te tiens au courant ;)

**Comment by ludovicm67** [comment]
@JLCochardSFA J'ai résolu les conflits avec `main` et j'ai mergé la PR.
Ça devrait être déployé très prochainement sur INT.

**Comment by ludovicm67** [comment]
C'est également en production. Je ferme le ticket, car tout est au vert :)
