### ISSUE TITLE
Merge Linked Data Day page

### ISSUE THREAD

**Issue by MFracassoSFA** [SwissFederalArchives/lindas-admin-ch#16]
Hello Ludovic

I just made some updates to this page in DE/FR: https://test.lindas.admin.ch/linked-data-day/?lang=de
As Jean-Luc described me, I have to contact you if I need any help.

Could you please merge/publish the new changes to the public version of the Website? Please make sure to publish them **on Monday, the 26th of February**. Not before.

I think we need to do a teams-meeting in the future, so I'm able to make such merges. For this case, I would be glad if you could do the merge.

Thank you very much!
Best regards
Mario

**Comment by ludovicm67** [comment]
Hello Mario,

The deployment process is described here: https://github.com/SwissFederalArchives/lindas-admin-ch?tab=readme-ov-file#deployment

If you create a Pull Request (`develop` → `main`) and merge it, this will deploy on INT.
To deploy on PROD, you will need to trigger the job manually.
Is it something you want to try?

That way, you will be able to trigger new deployments in the future if needed.

Best,
Ludovic.

**Comment by MFracassoSFA** [comment]
Hi Ludovic

Alright I think I understand. So, I have to choose the CI Workflow and choose the Branch "main" right? I will click "run workflow" it will publish the changes I made in develop right? Or is my understanding wrong?

Thanks in advance for your help.
Best
Mario

**Comment by ludovicm67** [comment]
Hi Mario,

This will deploy the current state of the `main` branch on INT and PROD.

So to deploy your changes from `develop` branch in PROD, you will first need to get your changes into the `main` branch ; this can be done using a Pull Request.
You can already prepare it if you want.

Once you merge the Pull Request on `main` this will deploy on INT.

To trigger the deployment to PROD, you will need to use the CI workflow and use the branch `main`, and then click on the "run the workflow" button.
This will rebuild INT (should not have any change), and publish on PROD.

Best,
Ludovic.

**Comment by ludovicm67** [comment]
Hi @MFracassoSFA!

I just want to know if you want to try to do it or if I need to do it.
It's not an issue for me.

Best,
Ludovic.

**Comment by MFracassoSFA** [comment]
Hi Ludovic

Thanks for your explanations! I will try it out, as soon as I'm allowed to publish the changes. It got posponed to end of this week.

I close this ticket for now.

Thank you very much!

Best regards
Mario

**Comment by ludovicm67** [comment]
Hi Mario,

Thank you for your update!
Ping me if you need me for anything :)

Best,
Ludovic.

**Comment by ludovicm67** [comment]
Hi @MFracassoSFA,

Any update on this?
I'm asking because I will need to upgrade the Trifid version in the next days (and also some other dependencies).
If there are some data that should not be published on INT/PROD, then I would be stuck with TEST only for now.
Do you have an estimate when your changes could be published on PROD?

Best,
Ludovic.

**Comment by ludovicm67** [comment]
Hi @MFracassoSFA,

I will need to push the changes at least on INT.
So I will take care of the PR for `develop` → `main` today.
Can you provide some feedback soon about the fact if we can deploy the changes on PROD?
Right now it's blocking us.

Best,
Ludovic.

**Comment by ludovicm67** [comment]
I created the PR #18 to deploy on INT. I'm merging it right now.

**Comment by MFracassoSFA** [comment]
Hi @ludovicm67 
I'm sorry for not responding to your comments. I was sick and wasn't in the office.
I think you've done the merge already so you don't need my ok anymore, right? :)

Best,
Mario

**Comment by ludovicm67** [comment]
Hi @MFracassoSFA,

Oh ok, thank you for your update, and I hope you are feeling better!
Currently, we are on TEST and INT, but not on PROD yet.
Can I deploy to PROD?

Best,
Ludovic.

**Comment by MFracassoSFA** [comment]
Hello @ludovicm67 
I'm doing way better than yesterday - thank you!
I'm currently clarifying, if we're allowed to go live with the changes I did last week.

I will let you know as soon as possible.

Best
Mario

**Comment by MFracassoSFA** [comment]
Hi @ludovicm67 
I just discussed this topic with my superior and we it is necessary that we won't go live before tuesday next week.
Is it possible for you to schedule the merge to PROD monday evening / tuesday morning of the whole site?

Thanks in advance for your response.

Best
Mario

**Comment by ludovicm67** [comment]
Hi @MFracassoSFA,

Thanks a lot for the info.
I will trigger the release for PROD Monday 11th in the evening or Tuesday 12th in the morning.
Is it OK for you?

Best,
Ludovic.

**Comment by MFracassoSFA** [comment]
Hello @ludovicm67 
Thats perfectly fine! Thank you so much and sorry for the wait time.
I'll do some more changes on the page tomorrow just for your info :)

Best
Mario

**Comment by ludovicm67** [comment]
Hi @MFracassoSFA,

It's deployed on INT and PROD now :)
And it includes your latest changes.

For info, I'm preparing the release of Lindas with the new version of Trifid.
I also fixed an issue with the content plugin ; it was missing some styles (and there were some spacing issues, and so on) ; can you check TEST (`develop` branch) and perform fixes if required?

Best,
Ludovic.

**Comment by ludovicm67** [comment]
Hi @MFracassoSFA!

Thank you for your feedback, it's great to have!
I will see if I can improve most of those points.

Regarding the update on the content, the TEST environment is now using the new version of Trifid.
I just want to collect some feedback from people that are using it in order to make sure that nothing was broken during the upgrade.
I will also need to do some preparation for PROD.

Is it OK if it's only deployed during the afternoon or tomorrow?

Best,
Ludovic.

**Comment by MFracassoSFA** [comment]
Hello @ludovicm67 

Thank you very much! These are just aestetic improvements, no hurries!

Im fine with this afternoon or tomorrow - thank you very much!

Best regards
Mario

**Comment by ludovicm67** [comment]
> - On https://test.lindas.admin.ch/ecosystem/ there's an unnecessary white space before the footer.
> - Same on https://test.lindas.admin.ch/data-usage/
> - https://test.lindas.admin.ch/governance/ same
> - https://test.lindas.admin.ch/know-how/ same
> - https://test.lindas.admin.ch/community/ same

Fixed!

> - Here's a huge space after the text (could be content-related) https://test.lindas.admin.ch/community/news/
> - Here as well: https://test.lindas.admin.ch/community/communication-channels/

I will let it that way for now, as this prevents the footer to appear in the middle of the screen. I can see to adjust it later.

**Comment by MFracassoSFA** [comment]
Thank you very much for the fixes! And I understand why you left it like that. Thats completely fine for me.
Do you need any more specific testing on the site? Let me know :)

Best
Mario

**Comment by ludovicm67** [comment]
I saw on some pages that `/static-assets/img/white-space-2.jpg` was used to do some spacing.
In TEST, I pushed a fix for adding the right style again on content, so I don't know if some of them can be removed now?

Like here: https://test.lindas.admin.ch/linked-data-day/?

Best,
Ludovic.

**Comment by MFracassoSFA** [comment]
I know that's odd to me aswell. Jean-Luc taught me I'd have to use this jpg to add spacing. But isn't there a solution like using "<br>" or something?

I think we can remove the white-space-jpg there aswell! What do you think?
Best,
Mario

**Comment by ludovicm67** [comment]
> I think we can remove the white-space-jpg there aswell! What do you think?

For now, I will suggest going through the content where this image is used, and see if it makes sense to remove it or not (maybe it can make some sense to keep it a some precise places).

Do you want to take care of it?

For the `<br>` tag, the sanitizer is removing them ; but in the future I can see to whitelist them.

> I've just seen - you even fixed the dropshadow beneath the table

This is done by the spacing image that is added. Removing the image will solve this issue ;)

Best,
Ludovic.

**Comment by MFracassoSFA** [comment]
I'll take care of it in the next few minutes and will give you feedback right after.

Sorry, I didn't notice that it's not allowed to use html tags in the normal text format here. But I see you still understood what was meant! :)

Oh nice to know. Thank you very much. You'll hear from me in a few minutes.

Best
Mario

**Comment by MFracassoSFA** [comment]
Hello @ludovicm67 
I removed the white space JPG's and it still seems to look fine! Thank you very much.

**Comment by ludovicm67** [comment]
Great, perfect! 👍

**Comment by ludovicm67** [comment]
@MFracassoSFA for info, I deployed it in all environments, as promised!

**Comment by MFracassoSFA** [comment]
@ludovicm67  Thank you very much, you're doing a great job! :)
I'll do some changes today on the french site - am I allowed to try to merge it by myself this time or do you have any work in progress that's holding us from publishing?

Nice working with you!
Best,
Mario

**Comment by MFracassoSFA** [comment]
Hello @ludovicm67 
I updated https://test.lindas.admin.ch/linked-data-day/?lang=fr
The table seems in the "hours"-column weird - do you know a way how I can get the times on one line?

Best,
Mario

**Comment by ludovicm67** [comment]
@MFracassoSFA Thank you, it's always nice to hear! :)
Yes, you can try to do the releases yourself, so that you can try the process!

Just for information, I will need to ship also a few updates (I will try to have them done today). But nothing that is very urgent/blocking so far.

So just release when you want, and I will make sure that what I push on the `develop` branch is safe to deploy up to PROD ;)

> I updated https://test.lindas.admin.ch/linked-data-day/?lang=fr
> The table seems in the "hours"-column weird - do you know a way how I can get the times on one line?

I would suggest to just remove the spaces around `h` ; that's the easiest fix for it.

**Comment by MFracassoSFA** [comment]
@ludovicm67 Alright thank you! I'm not sure if I'll be able to do the release today so if you're earlier and ready to publish, just go for it. I'll inform you as soon as I'd be releasing :)

About the spacing, I'll try that! I hope that's okay without spacing for french speaking people? :)

Best
Mario

**Comment by ludovicm67** [comment]
> @ludovicm67 Alright thank you! I'm not sure if I'll be able to do the release today so if you're earlier and ready to publish, just go for it. I'll inform you as soon as I'd be releasing :)

Since there is nothing urgent anymore from my side, I think it would be great that you can finally try the process ;p

> About the spacing, I'll try that! I hope that's okay without spacing for french speaking people? :)

I'm French, and it's not an issue for me to see it formatted without the spaces.
I think that the right character to use should be non-breaking spaces.
Maybe this is something we can try?

Best,
Ludovic.

**Comment by ludovicm67** [comment]
I tried using non-breaking spaces, and it seems to be working :)

**Comment by ludovicm67** [comment]
I will need to deploy a fix on all environments, so I will need to deploy very soon.

**Comment by MFracassoSFA** [comment]
@ludovicm67  wow great thank you so much! You can deplay whenever you want no problem :)

**Comment by MFracassoSFA** [comment]
Hi @ludovicm67 
I made a small change to https://lindas.admin.ch/linked-data-day/?lang=de
The picture was in french instead of german.
Am I allowed to merge or do you want to do it as I dont know if you have updates in your pipeline.

Best,
Mario

**Comment by ludovicm67** [comment]
Hi @MFracassoSFA!

I don't have any changes on my side.
Feel free to merge to main to deploy on INT, and to trigger the workflow then to deploy on PROD.

Best,
Ludovic.

**Comment by MFracassoSFA** [comment]
Hi @ludovicm67 
Great thank you so much for your help and the great explanation!

Best,
Mario
