### ISSUE TITLE
Mise en commentaire de la page test.lindas.admin.ch/visualize/

### ISSUE THREAD

**Issue by JLCochardSFA** [SwissFederalArchives/lindas-admin-ch#23]
@ludovicm67 Hello, j'ai vu que tu avais mis en commentaire dans config.yaml l'entrée de la page test.lindas.admin.ch/visualize/.
Est-ce que cela posait un problème? Je ne souhaite pas que cette page soit liée à un menu mais je voulais l'utiliser pour démontrer comment intégrer des graphiques de visualize.admin.ch dans des pages web.
Est-ce que je peux la réactiver en test pour demain ou y a-t-il un problème avec ma manière de configurer la page??

Salutations,
Jean-Luc

**Comment by ludovicm67** [comment]
Hello @JLCochardSFA !

Hier et aujourd'hui, on est en plein dans la mise à jour de la version de Trifid dans tous les environnements.
Il y a encore quelques petits ajustements à faire, et je souhaite que tout puisse être déployé partout pour être sûr que tout est bon.
C'est-à-dire que tout ce qui est sur TEST, sera dans INT et dans PROD, y compris tout ce qui est "work in progress" depuis hier (j'ai exprès attendu que tout soit OK du côté de Marco au niveau du contenu pour pouvoir aller en production).

Concernant les changements que tu as faits hier, il y avait différents soucis : 
- l'indentation n'était pas bonne dans le fichier de configuration, ce qui empêche Trifid de se lancer ; j'ai fait la correction hier directement
- une entrée pour du contenu qui serait monté dans `/visualize` a été ajoutée, mais comme il n'y a pas de contenu dans `./content/visualize/`, Trifid ne se lance pas ; j'ai donc commenté cette partie https://github.com/SwissFederalArchives/lindas-admin-ch/blob/839c05b426edd2075c71dc2f318b8783b375921a/config.yaml#L182-L184 (que j'avais un moment décommenté quand tu avais créé un fichier dans le dossier en question, mais que j'ai dû commenter à nouveau quand tu as retiré ce fichier)
- et il y a cette entrée dans le fichier de configuration https://github.com/SwissFederalArchives/lindas-admin-ch/blob/839c05b426edd2075c71dc2f318b8783b375921a/config.yaml#L75-L79 qui crée la page `/visualize` à partir du fichier `views/visualize.hbs`. Cependant, quand on accède à `/visualize/`, on voit qu'il y a une erreur 500. Cela est dû au fait qu'il y ait des erreurs dans le fichier `views/visualize.hbs`. Je vais voir pour faire les corrections pour ça ;)

Les changements cassants ont heureusement pu être détectés à temps grâce aux quelques tests que j'ai mis en place, ce qui empêchait le déploiement de ces versions.

Bonne journée,
Ludovic.

**Comment by ludovicm67** [comment]
> Cependant, quand on accède à /visualize/, on voit qu'il y a une erreur 500. Cela est dû au fait qu'il y ait des erreurs dans le fichier views/visualize.hbs. Je vais voir pour faire les corrections pour ça ;)

Pour info, je viens de pousser un commit pour corriger ça : faf8106b49dbf9ae2cf54626065bbfd5d07146c8

**Comment by ludovicm67** [comment]
https://test.lindas.admin.ch/visualize/
