### ISSUE TITLE
Adapter la taille des caractères d'un paragraphe

### ISSUE THREAD

**Issue by JLCochardSFA** [SwissFederalArchives/lindas-admin-ch#31]
@ludovicm67 Existe-t-il un moyen en MD de réduire la taille des caractères d'un paragraphe?

**Comment by ludovicm67** [comment]
Non, pas vraiment.

Le Markdown permet de rédiger du contenu texte avec différents niveaux de titres, d'insérer des images, des liens, des listes, du code, des citations et des tableaux, ce qui devrait être suffisant pour la majorité des cas.
