### ISSUE TITLE
Do some cleanup in the branches

### ISSUE THREAD

**Issue by ludovicm67** [SwissFederalArchives/lindas-admin-ch#4]
Hi @JLCochardSFA,

It seems that you created many branches for some fixes here and there.
Can you merge the ones that need to be merged on `develop` for example and delete all that can be removed?

Here is the list of all branches that needs to be checked:

- [x] [jeanluc.cochard-main-patch-07299](https://github.com/SwissFederalArchives/lindas-admin-ch/tree/jeanluc.cochard-main-patch-07299)
- [x] [jeanluc.cochard-main-patch-28058](https://github.com/SwissFederalArchives/lindas-admin-ch/tree/jeanluc.cochard-main-patch-28058)
- [x] [jeanluc.cochard-main-patch-30957](https://github.com/SwissFederalArchives/lindas-admin-ch/tree/jeanluc.cochard-main-patch-30957)
- [x] [jeanluc.cochard-main-patch-36878](https://github.com/SwissFederalArchives/lindas-admin-ch/tree/jeanluc.cochard-main-patch-36878)
- [x] [jeanluc.cochard-main-patch-68518](https://github.com/SwissFederalArchives/lindas-admin-ch/tree/jeanluc.cochard-main-patch-68518)
- [x] [jeanluc.cochard-main-patch-75985](https://github.com/SwissFederalArchives/lindas-admin-ch/tree/jeanluc.cochard-main-patch-75985)
- [x] [jeanluc.cochard-main-patch-82229](https://github.com/SwissFederalArchives/lindas-admin-ch/tree/jeanluc.cochard-main-patch-82229)

If you need someone for reviewing them, just create PRs and assign them to someone relevant.

That way, the repository will be in a clean state.

**Comment by JLCochardSFA** [comment]
Je ne sais pas pourquoi il y a toutes ces branches. Rien dans le contenu de ces modifications ne semble utile. J'ai tout effacé

**Comment by ludovicm67** [comment]
Je suppose que ces branches ont été automatiquement créées depuis GitLab quand des modifications ont été faites.

Merci pour avoir fait le tri, je ferme ce ticket !
