### ISSUE TITLE
Modification du contenu du site

### ISSUE THREAD

**Issue by JLCochardSFA** [SwissFederalArchives/lindas-admin-ch#7]
Bonjour, est-ce que je peux faire des changements dans le contenu du site? Est-ce que cela se fait via la même procédure qu'avec Gitlab?
@ludovicm67

**Comment by ludovicm67** [comment]
Bonjour @JLCochardSFA, oui les changements sont possibles de la même manière qu'avec GitLab (sauf pour le déploiement de PROD) ; la documentation a été mise à jour ici : https://github.com/SwissFederalArchives/lindas-admin-ch?tab=readme-ov-file#deployment.

**Comment by ludovicm67** [comment]
Merci @JLCochardSFA pour le tri dans les branches !

Concernant les changements de contenu, par environement : 
- TEST: commit sur `develop`
- INT: commit sur `main`
- PROD: commit sur `main` + lancer un job manuel, comme décrit dans [la documentation](https://github.com/SwissFederalArchives/lindas-admin-ch?tab=readme-ov-file#deployment)

Après il est préférable de travailler sur des branches à part (de préférence basée sur `develop`) et de demander à quelqu'un en relecture, avant de faire un merge sur `develop`.

Une fois que `develop` (donc TEST) est dans un état convenable, il est possible de déployer sur INT et PROD ensuite, en faisant un merge de `develop` vers `main`.

Est-ce qu'il y a d'autres questions à ce sujet, ou tout est bon ?
